services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: home_assistant_user
      POSTGRES_PASSWORD: home_assistant_password
      POSTGRES_DB: home_assistant
    volumes:
      - ./db-data/:/var/lib/postgresql
      - ./db-init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U home_assistant_user -d home_assistant"]
      interval: 5s
      timeout: 5s
      retries: 5
