services:
  backend:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: home_assistant_user
      POSTGRES_PASSWORD: home_assistant_password
      POSTGRES_DB: home_assistant
    volumes:
      - ./db-data/:/var/lib/postgresql
      - ./db-init/:/docker-entrypoint-initdb.d/
